FROM python:3.6

ADD assignment3_part1.py /

RUN pip install jupyter
RUN pip install pandas 
RUN pip install seaborn 
RUN pip install matplotlib
RUN pip install numpy 
RUN pip install mechanicalsoup
RUN pip install pathlib
RUN pip install shutil
RUN pip installurllib
RUN pip install zipfile
RUN pip install logging 
RUN pip install tabulate
RUN pip install requests
RUN pip install webbrowser
	
CMD ["sh" , "/assignment3/part1_run.sh"]